version: '2.23.3'

services:

  django:
    build: .
    expose:
      - '8000'
    ports:
      - '8000:8000'
    container_name: django
    env_file:
      - ./app/config/.env

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    container_name: postgres
    env_file:
      - ./app/config/.env
    volumes:
      - /home/kdu/postgresql/data:/var/lib/postgresql/data/
  
  nginx:
    image: nginx:1.19.2
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./app/static:/data/static:ro
    depends_on:
      - django


